package com.onboarding.project.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

public final class Device {
  private Device() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceReadingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeviceReading)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 deviceReading = 1;</code>
     * @return The deviceReading.
     */
    long getDeviceReading();

    /**
     * <code>string deviceID = 2;</code>
     * @return The deviceID.
     */
    java.lang.String getDeviceID();
    /**
     * <code>string deviceID = 2;</code>
     * @return The bytes for deviceID.
     */
    com.google.protobuf.ByteString
        getDeviceIDBytes();

    /**
     * <code>int64 deviceDatetime = 3;</code>
     * @return The deviceDatetime.
     */
    long getDeviceDatetime();
  }
  /**
   * Protobuf type {@code DeviceReading}
   */
  public static final class DeviceReading extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DeviceReading)
      DeviceReadingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceReading.newBuilder() to construct.
    private DeviceReading(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceReading() {
      deviceID_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeviceReading();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceReading(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              deviceReading_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceID_ = s;
              break;
            }
            case 24: {

              deviceDatetime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Device.internal_static_DeviceReading_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Device.internal_static_DeviceReading_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Device.DeviceReading.class, Device.DeviceReading.Builder.class);
    }

    public static final int DEVICEREADING_FIELD_NUMBER = 1;
    private long deviceReading_;
    /**
     * <code>int64 deviceReading = 1;</code>
     * @return The deviceReading.
     */
    @java.lang.Override
    public long getDeviceReading() {
      return deviceReading_;
    }

    public static final int DEVICEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceID_;
    /**
     * <code>string deviceID = 2;</code>
     * @return The deviceID.
     */
    @java.lang.Override
    public java.lang.String getDeviceID() {
      java.lang.Object ref = deviceID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceID_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceID = 2;</code>
     * @return The bytes for deviceID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIDBytes() {
      java.lang.Object ref = deviceID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEDATETIME_FIELD_NUMBER = 3;
    private long deviceDatetime_;
    /**
     * <code>int64 deviceDatetime = 3;</code>
     * @return The deviceDatetime.
     */
    @java.lang.Override
    public long getDeviceDatetime() {
      return deviceDatetime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (deviceReading_ != 0L) {
        output.writeInt64(1, deviceReading_);
      }
      if (!getDeviceIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceID_);
      }
      if (deviceDatetime_ != 0L) {
        output.writeInt64(3, deviceDatetime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (deviceReading_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, deviceReading_);
      }
      if (!getDeviceIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceID_);
      }
      if (deviceDatetime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, deviceDatetime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Device.DeviceReading)) {
        return super.equals(obj);
      }
      Device.DeviceReading other = (Device.DeviceReading) obj;

      if (getDeviceReading()
          != other.getDeviceReading()) return false;
      if (!getDeviceID()
          .equals(other.getDeviceID())) return false;
      if (getDeviceDatetime()
          != other.getDeviceDatetime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEREADING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDeviceReading());
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceID().hashCode();
      hash = (37 * hash) + DEVICEDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDeviceDatetime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Device.DeviceReading parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Device.DeviceReading parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Device.DeviceReading parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Device.DeviceReading parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Device.DeviceReading parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Device.DeviceReading parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Device.DeviceReading parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Device.DeviceReading parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Device.DeviceReading parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Device.DeviceReading parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Device.DeviceReading parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Device.DeviceReading parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Device.DeviceReading prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeviceReading}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeviceReading)
        Device.DeviceReadingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Device.internal_static_DeviceReading_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Device.internal_static_DeviceReading_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Device.DeviceReading.class, Device.DeviceReading.Builder.class);
      }

      // Construct using Device.DeviceReading.newBuilder()
      public Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceReading_ = 0L;

        deviceID_ = "";

        deviceDatetime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Device.internal_static_DeviceReading_descriptor;
      }

      @java.lang.Override
      public Device.DeviceReading getDefaultInstanceForType() {
        return Device.DeviceReading.getDefaultInstance();
      }

      @java.lang.Override
      public Device.DeviceReading build() {
        Device.DeviceReading result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Device.DeviceReading buildPartial() {
        Device.DeviceReading result = new Device.DeviceReading(this);
        result.deviceReading_ = deviceReading_;
        result.deviceID_ = deviceID_;
        result.deviceDatetime_ = deviceDatetime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Device.DeviceReading) {
          return mergeFrom((Device.DeviceReading)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Device.DeviceReading other) {
        if (other == Device.DeviceReading.getDefaultInstance()) return this;
        if (other.getDeviceReading() != 0L) {
          setDeviceReading(other.getDeviceReading());
        }
        if (!other.getDeviceID().isEmpty()) {
          deviceID_ = other.deviceID_;
          onChanged();
        }
        if (other.getDeviceDatetime() != 0L) {
          setDeviceDatetime(other.getDeviceDatetime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Device.DeviceReading parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Device.DeviceReading) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long deviceReading_ ;
      /**
       * <code>int64 deviceReading = 1;</code>
       * @return The deviceReading.
       */
      @java.lang.Override
      public long getDeviceReading() {
        return deviceReading_;
      }
      /**
       * <code>int64 deviceReading = 1;</code>
       * @param value The deviceReading to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceReading(long value) {
        
        deviceReading_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 deviceReading = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceReading() {
        
        deviceReading_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object deviceID_ = "";
      /**
       * <code>string deviceID = 2;</code>
       * @return The deviceID.
       */
      public java.lang.String getDeviceID() {
        java.lang.Object ref = deviceID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deviceID = 2;</code>
       * @return The bytes for deviceID.
       */
      public com.google.protobuf.ByteString
          getDeviceIDBytes() {
        java.lang.Object ref = deviceID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceID = 2;</code>
       * @param value The deviceID to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceID() {
        
        deviceID_ = getDefaultInstance().getDeviceID();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceID = 2;</code>
       * @param value The bytes for deviceID to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceID_ = value;
        onChanged();
        return this;
      }

      private long deviceDatetime_ ;
      /**
       * <code>int64 deviceDatetime = 3;</code>
       * @return The deviceDatetime.
       */
      @java.lang.Override
      public long getDeviceDatetime() {
        return deviceDatetime_;
      }
      /**
       * <code>int64 deviceDatetime = 3;</code>
       * @param value The deviceDatetime to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceDatetime(long value) {
        
        deviceDatetime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 deviceDatetime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceDatetime() {
        
        deviceDatetime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DeviceReading)
    }

    // @@protoc_insertion_point(class_scope:DeviceReading)
    private static final Device.DeviceReading DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Device.DeviceReading();
    }

    public static Device.DeviceReading getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceReading>
        PARSER = new com.google.protobuf.AbstractParser<DeviceReading>() {
      @java.lang.Override
      public DeviceReading parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceReading(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceReading> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceReading> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Device.DeviceReading getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface replyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:reply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestID = 1;</code>
     * @return The requestID.
     */
    java.lang.String getRequestID();
    /**
     * <code>string requestID = 1;</code>
     * @return The bytes for requestID.
     */
    com.google.protobuf.ByteString
        getRequestIDBytes();

    /**
     * <code>.DeviceReading deviceReading = 2;</code>
     * @return Whether the deviceReading field is set.
     */
    boolean hasDeviceReading();
    /**
     * <code>.DeviceReading deviceReading = 2;</code>
     * @return The deviceReading.
     */
    Device.DeviceReading getDeviceReading();
    /**
     * <code>.DeviceReading deviceReading = 2;</code>
     */
    Device.DeviceReadingOrBuilder getDeviceReadingOrBuilder();

    /**
     * <code>int64 status = 3;</code>
     * @return The status.
     */
    long getStatus();
  }
  /**
   * Protobuf type {@code reply}
   */
  public static final class reply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:reply)
      replyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use reply.newBuilder() to construct.
    private reply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private reply() {
      requestID_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new reply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestID_ = s;
              break;
            }
            case 18: {
              Device.DeviceReading.Builder subBuilder = null;
              if (deviceReading_ != null) {
                subBuilder = deviceReading_.toBuilder();
              }
              deviceReading_ = input.readMessage(Device.DeviceReading.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deviceReading_);
                deviceReading_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              status_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Device.internal_static_reply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Device.internal_static_reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Device.reply.class, Device.reply.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestID_;
    /**
     * <code>string requestID = 1;</code>
     * @return The requestID.
     */
    @java.lang.Override
    public java.lang.String getRequestID() {
      java.lang.Object ref = requestID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestID_ = s;
        return s;
      }
    }
    /**
     * <code>string requestID = 1;</code>
     * @return The bytes for requestID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIDBytes() {
      java.lang.Object ref = requestID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEREADING_FIELD_NUMBER = 2;
    private Device.DeviceReading deviceReading_;
    /**
     * <code>.DeviceReading deviceReading = 2;</code>
     * @return Whether the deviceReading field is set.
     */
    @java.lang.Override
    public boolean hasDeviceReading() {
      return deviceReading_ != null;
    }
    /**
     * <code>.DeviceReading deviceReading = 2;</code>
     * @return The deviceReading.
     */
    @java.lang.Override
    public Device.DeviceReading getDeviceReading() {
      return deviceReading_ == null ? Device.DeviceReading.getDefaultInstance() : deviceReading_;
    }
    /**
     * <code>.DeviceReading deviceReading = 2;</code>
     */
    @java.lang.Override
    public Device.DeviceReadingOrBuilder getDeviceReadingOrBuilder() {
      return getDeviceReading();
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private long status_;
    /**
     * <code>int64 status = 3;</code>
     * @return The status.
     */
    @java.lang.Override
    public long getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestID_);
      }
      if (deviceReading_ != null) {
        output.writeMessage(2, getDeviceReading());
      }
      if (status_ != 0L) {
        output.writeInt64(3, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestID_);
      }
      if (deviceReading_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDeviceReading());
      }
      if (status_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Device.reply)) {
        return super.equals(obj);
      }
      Device.reply other = (Device.reply) obj;

      if (!getRequestID()
          .equals(other.getRequestID())) return false;
      if (hasDeviceReading() != other.hasDeviceReading()) return false;
      if (hasDeviceReading()) {
        if (!getDeviceReading()
            .equals(other.getDeviceReading())) return false;
      }
      if (getStatus()
          != other.getStatus()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestID().hashCode();
      if (hasDeviceReading()) {
        hash = (37 * hash) + DEVICEREADING_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceReading().hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStatus());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Device.reply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Device.reply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Device.reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Device.reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Device.reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Device.reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Device.reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Device.reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Device.reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Device.reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Device.reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Device.reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Device.reply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:reply)
        Device.replyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Device.internal_static_reply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Device.internal_static_reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Device.reply.class, Device.reply.Builder.class);
      }

      // Construct using Device.reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestID_ = "";

        if (deviceReadingBuilder_ == null) {
          deviceReading_ = null;
        } else {
          deviceReading_ = null;
          deviceReadingBuilder_ = null;
        }
        status_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Device.internal_static_reply_descriptor;
      }

      @java.lang.Override
      public Device.reply getDefaultInstanceForType() {
        return Device.reply.getDefaultInstance();
      }

      @java.lang.Override
      public Device.reply build() {
        Device.reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Device.reply buildPartial() {
        Device.reply result = new Device.reply(this);
        result.requestID_ = requestID_;
        if (deviceReadingBuilder_ == null) {
          result.deviceReading_ = deviceReading_;
        } else {
          result.deviceReading_ = deviceReadingBuilder_.build();
        }
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Device.reply) {
          return mergeFrom((Device.reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Device.reply other) {
        if (other == Device.reply.getDefaultInstance()) return this;
        if (!other.getRequestID().isEmpty()) {
          requestID_ = other.requestID_;
          onChanged();
        }
        if (other.hasDeviceReading()) {
          mergeDeviceReading(other.getDeviceReading());
        }
        if (other.getStatus() != 0L) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Device.reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Device.reply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestID_ = "";
      /**
       * <code>string requestID = 1;</code>
       * @return The requestID.
       */
      public java.lang.String getRequestID() {
        java.lang.Object ref = requestID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestID = 1;</code>
       * @return The bytes for requestID.
       */
      public com.google.protobuf.ByteString
          getRequestIDBytes() {
        java.lang.Object ref = requestID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestID = 1;</code>
       * @param value The requestID to set.
       * @return This builder for chaining.
       */
      public Builder setRequestID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestID() {
        
        requestID_ = getDefaultInstance().getRequestID();
        onChanged();
        return this;
      }
      /**
       * <code>string requestID = 1;</code>
       * @param value The bytes for requestID to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestID_ = value;
        onChanged();
        return this;
      }

      private Device.DeviceReading deviceReading_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Device.DeviceReading, Device.DeviceReading.Builder, Device.DeviceReadingOrBuilder> deviceReadingBuilder_;
      /**
       * <code>.DeviceReading deviceReading = 2;</code>
       * @return Whether the deviceReading field is set.
       */
      public boolean hasDeviceReading() {
        return deviceReadingBuilder_ != null || deviceReading_ != null;
      }
      /**
       * <code>.DeviceReading deviceReading = 2;</code>
       * @return The deviceReading.
       */
      public Device.DeviceReading getDeviceReading() {
        if (deviceReadingBuilder_ == null) {
          return deviceReading_ == null ? Device.DeviceReading.getDefaultInstance() : deviceReading_;
        } else {
          return deviceReadingBuilder_.getMessage();
        }
      }
      /**
       * <code>.DeviceReading deviceReading = 2;</code>
       */
      public Builder setDeviceReading(Device.DeviceReading value) {
        if (deviceReadingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deviceReading_ = value;
          onChanged();
        } else {
          deviceReadingBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.DeviceReading deviceReading = 2;</code>
       */
      public Builder setDeviceReading(
          Device.DeviceReading.Builder builderForValue) {
        if (deviceReadingBuilder_ == null) {
          deviceReading_ = builderForValue.build();
          onChanged();
        } else {
          deviceReadingBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.DeviceReading deviceReading = 2;</code>
       */
      public Builder mergeDeviceReading(Device.DeviceReading value) {
        if (deviceReadingBuilder_ == null) {
          if (deviceReading_ != null) {
            deviceReading_ =
              Device.DeviceReading.newBuilder(deviceReading_).mergeFrom(value).buildPartial();
          } else {
            deviceReading_ = value;
          }
          onChanged();
        } else {
          deviceReadingBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.DeviceReading deviceReading = 2;</code>
       */
      public Builder clearDeviceReading() {
        if (deviceReadingBuilder_ == null) {
          deviceReading_ = null;
          onChanged();
        } else {
          deviceReading_ = null;
          deviceReadingBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.DeviceReading deviceReading = 2;</code>
       */
      public Device.DeviceReading.Builder getDeviceReadingBuilder() {
        
        onChanged();
        return getDeviceReadingFieldBuilder().getBuilder();
      }
      /**
       * <code>.DeviceReading deviceReading = 2;</code>
       */
      public Device.DeviceReadingOrBuilder getDeviceReadingOrBuilder() {
        if (deviceReadingBuilder_ != null) {
          return deviceReadingBuilder_.getMessageOrBuilder();
        } else {
          return deviceReading_ == null ?
              Device.DeviceReading.getDefaultInstance() : deviceReading_;
        }
      }
      /**
       * <code>.DeviceReading deviceReading = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Device.DeviceReading, Device.DeviceReading.Builder, Device.DeviceReadingOrBuilder> 
          getDeviceReadingFieldBuilder() {
        if (deviceReadingBuilder_ == null) {
          deviceReadingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Device.DeviceReading, Device.DeviceReading.Builder, Device.DeviceReadingOrBuilder>(
                  getDeviceReading(),
                  getParentForChildren(),
                  isClean());
          deviceReading_ = null;
        }
        return deviceReadingBuilder_;
      }

      private long status_ ;
      /**
       * <code>int64 status = 3;</code>
       * @return The status.
       */
      @java.lang.Override
      public long getStatus() {
        return status_;
      }
      /**
       * <code>int64 status = 3;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(long value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:reply)
    }

    // @@protoc_insertion_point(class_scope:reply)
    private static final Device.reply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Device.reply();
    }

    public static Device.reply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<reply>
        PARSER = new com.google.protobuf.AbstractParser<reply>() {
      @java.lang.Override
      public reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new reply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<reply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<reply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Device.reply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestID = 1;</code>
     * @return The requestID.
     */
    java.lang.String getRequestID();
    /**
     * <code>string requestID = 1;</code>
     * @return The bytes for requestID.
     */
    com.google.protobuf.ByteString
        getRequestIDBytes();

    /**
     * <code>.request.RequestType requestType = 2;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    int getRequestTypeValue();
    /**
     * <code>.request.RequestType requestType = 2;</code>
     * @return The requestType.
     */
    Device.request.RequestType getRequestType();

    /**
     * <code>int64 deviceDatetime = 3;</code>
     * @return The deviceDatetime.
     */
    long getDeviceDatetime();

    /**
     * <code>int64 deviceID = 4;</code>
     * @return The deviceID.
     */
    long getDeviceID();

    /**
     * <code>.DeviceReading deviceReading = 5;</code>
     * @return Whether the deviceReading field is set.
     */
    boolean hasDeviceReading();
    /**
     * <code>.DeviceReading deviceReading = 5;</code>
     * @return The deviceReading.
     */
    Device.DeviceReading getDeviceReading();
    /**
     * <code>.DeviceReading deviceReading = 5;</code>
     */
    Device.DeviceReadingOrBuilder getDeviceReadingOrBuilder();
  }
  /**
   * Protobuf type {@code request}
   */
  public static final class request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:request)
      requestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use request.newBuilder() to construct.
    private request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private request() {
      requestID_ = "";
      requestType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestID_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              requestType_ = rawValue;
              break;
            }
            case 24: {

              deviceDatetime_ = input.readInt64();
              break;
            }
            case 32: {

              deviceID_ = input.readInt64();
              break;
            }
            case 42: {
              Device.DeviceReading.Builder subBuilder = null;
              if (deviceReading_ != null) {
                subBuilder = deviceReading_.toBuilder();
              }
              deviceReading_ = input.readMessage(Device.DeviceReading.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deviceReading_);
                deviceReading_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Device.internal_static_request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Device.internal_static_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Device.request.class, Device.request.Builder.class);
    }

    /**
     * Protobuf enum {@code request.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INITIALIZATION = 0;</code>
       */
      INITIALIZATION(0),
      /**
       * <code>CONTROL = 1;</code>
       */
      CONTROL(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>INITIALIZATION = 0;</code>
       */
      public static final int INITIALIZATION_VALUE = 0;
      /**
       * <code>CONTROL = 1;</code>
       */
      public static final int CONTROL_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RequestType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static RequestType forNumber(int value) {
        switch (value) {
          case 0: return INITIALIZATION;
          case 1: return CONTROL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RequestType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Device.request.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RequestType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:request.RequestType)
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestID_;
    /**
     * <code>string requestID = 1;</code>
     * @return The requestID.
     */
    @java.lang.Override
    public java.lang.String getRequestID() {
      java.lang.Object ref = requestID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestID_ = s;
        return s;
      }
    }
    /**
     * <code>string requestID = 1;</code>
     * @return The bytes for requestID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIDBytes() {
      java.lang.Object ref = requestID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTTYPE_FIELD_NUMBER = 2;
    private int requestType_;
    /**
     * <code>.request.RequestType requestType = 2;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    @java.lang.Override public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.request.RequestType requestType = 2;</code>
     * @return The requestType.
     */
    @java.lang.Override public Device.request.RequestType getRequestType() {
      @SuppressWarnings("deprecation")
      Device.request.RequestType result = Device.request.RequestType.valueOf(requestType_);
      return result == null ? Device.request.RequestType.UNRECOGNIZED : result;
    }

    public static final int DEVICEDATETIME_FIELD_NUMBER = 3;
    private long deviceDatetime_;
    /**
     * <code>int64 deviceDatetime = 3;</code>
     * @return The deviceDatetime.
     */
    @java.lang.Override
    public long getDeviceDatetime() {
      return deviceDatetime_;
    }

    public static final int DEVICEID_FIELD_NUMBER = 4;
    private long deviceID_;
    /**
     * <code>int64 deviceID = 4;</code>
     * @return The deviceID.
     */
    @java.lang.Override
    public long getDeviceID() {
      return deviceID_;
    }

    public static final int DEVICEREADING_FIELD_NUMBER = 5;
    private Device.DeviceReading deviceReading_;
    /**
     * <code>.DeviceReading deviceReading = 5;</code>
     * @return Whether the deviceReading field is set.
     */
    @java.lang.Override
    public boolean hasDeviceReading() {
      return deviceReading_ != null;
    }
    /**
     * <code>.DeviceReading deviceReading = 5;</code>
     * @return The deviceReading.
     */
    @java.lang.Override
    public Device.DeviceReading getDeviceReading() {
      return deviceReading_ == null ? Device.DeviceReading.getDefaultInstance() : deviceReading_;
    }
    /**
     * <code>.DeviceReading deviceReading = 5;</code>
     */
    @java.lang.Override
    public Device.DeviceReadingOrBuilder getDeviceReadingOrBuilder() {
      return getDeviceReading();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestID_);
      }
      if (requestType_ != Device.request.RequestType.INITIALIZATION.getNumber()) {
        output.writeEnum(2, requestType_);
      }
      if (deviceDatetime_ != 0L) {
        output.writeInt64(3, deviceDatetime_);
      }
      if (deviceID_ != 0L) {
        output.writeInt64(4, deviceID_);
      }
      if (deviceReading_ != null) {
        output.writeMessage(5, getDeviceReading());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestID_);
      }
      if (requestType_ != Device.request.RequestType.INITIALIZATION.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, requestType_);
      }
      if (deviceDatetime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, deviceDatetime_);
      }
      if (deviceID_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, deviceID_);
      }
      if (deviceReading_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getDeviceReading());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Device.request)) {
        return super.equals(obj);
      }
      Device.request other = (Device.request) obj;

      if (!getRequestID()
          .equals(other.getRequestID())) return false;
      if (requestType_ != other.requestType_) return false;
      if (getDeviceDatetime()
          != other.getDeviceDatetime()) return false;
      if (getDeviceID()
          != other.getDeviceID()) return false;
      if (hasDeviceReading() != other.hasDeviceReading()) return false;
      if (hasDeviceReading()) {
        if (!getDeviceReading()
            .equals(other.getDeviceReading())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestID().hashCode();
      hash = (37 * hash) + REQUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + requestType_;
      hash = (37 * hash) + DEVICEDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDeviceDatetime());
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDeviceID());
      if (hasDeviceReading()) {
        hash = (37 * hash) + DEVICEREADING_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceReading().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Device.request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Device.request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Device.request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Device.request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Device.request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Device.request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Device.request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Device.request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Device.request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Device.request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Device.request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Device.request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Device.request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:request)
        Device.requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Device.internal_static_request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Device.internal_static_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Device.request.class, Device.request.Builder.class);
      }

      // Construct using Device.request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestID_ = "";

        requestType_ = 0;

        deviceDatetime_ = 0L;

        deviceID_ = 0L;

        if (deviceReadingBuilder_ == null) {
          deviceReading_ = null;
        } else {
          deviceReading_ = null;
          deviceReadingBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Device.internal_static_request_descriptor;
      }

      @java.lang.Override
      public Device.request getDefaultInstanceForType() {
        return Device.request.getDefaultInstance();
      }

      @java.lang.Override
      public Device.request build() {
        Device.request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Device.request buildPartial() {
        Device.request result = new Device.request(this);
        result.requestID_ = requestID_;
        result.requestType_ = requestType_;
        result.deviceDatetime_ = deviceDatetime_;
        result.deviceID_ = deviceID_;
        if (deviceReadingBuilder_ == null) {
          result.deviceReading_ = deviceReading_;
        } else {
          result.deviceReading_ = deviceReadingBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Device.request) {
          return mergeFrom((Device.request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Device.request other) {
        if (other == Device.request.getDefaultInstance()) return this;
        if (!other.getRequestID().isEmpty()) {
          requestID_ = other.requestID_;
          onChanged();
        }
        if (other.requestType_ != 0) {
          setRequestTypeValue(other.getRequestTypeValue());
        }
        if (other.getDeviceDatetime() != 0L) {
          setDeviceDatetime(other.getDeviceDatetime());
        }
        if (other.getDeviceID() != 0L) {
          setDeviceID(other.getDeviceID());
        }
        if (other.hasDeviceReading()) {
          mergeDeviceReading(other.getDeviceReading());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Device.request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Device.request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestID_ = "";
      /**
       * <code>string requestID = 1;</code>
       * @return The requestID.
       */
      public java.lang.String getRequestID() {
        java.lang.Object ref = requestID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestID = 1;</code>
       * @return The bytes for requestID.
       */
      public com.google.protobuf.ByteString
          getRequestIDBytes() {
        java.lang.Object ref = requestID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestID = 1;</code>
       * @param value The requestID to set.
       * @return This builder for chaining.
       */
      public Builder setRequestID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestID() {
        
        requestID_ = getDefaultInstance().getRequestID();
        onChanged();
        return this;
      }
      /**
       * <code>string requestID = 1;</code>
       * @param value The bytes for requestID to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestID_ = value;
        onChanged();
        return this;
      }

      private int requestType_ = 0;
      /**
       * <code>.request.RequestType requestType = 2;</code>
       * @return The enum numeric value on the wire for requestType.
       */
      @java.lang.Override public int getRequestTypeValue() {
        return requestType_;
      }
      /**
       * <code>.request.RequestType requestType = 2;</code>
       * @param value The enum numeric value on the wire for requestType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestTypeValue(int value) {
        
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.request.RequestType requestType = 2;</code>
       * @return The requestType.
       */
      @java.lang.Override
      public Device.request.RequestType getRequestType() {
        @SuppressWarnings("deprecation")
        Device.request.RequestType result = Device.request.RequestType.valueOf(requestType_);
        return result == null ? Device.request.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.request.RequestType requestType = 2;</code>
       * @param value The requestType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestType(Device.request.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        requestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.request.RequestType requestType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestType() {
        
        requestType_ = 0;
        onChanged();
        return this;
      }

      private long deviceDatetime_ ;
      /**
       * <code>int64 deviceDatetime = 3;</code>
       * @return The deviceDatetime.
       */
      @java.lang.Override
      public long getDeviceDatetime() {
        return deviceDatetime_;
      }
      /**
       * <code>int64 deviceDatetime = 3;</code>
       * @param value The deviceDatetime to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceDatetime(long value) {
        
        deviceDatetime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 deviceDatetime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceDatetime() {
        
        deviceDatetime_ = 0L;
        onChanged();
        return this;
      }

      private long deviceID_ ;
      /**
       * <code>int64 deviceID = 4;</code>
       * @return The deviceID.
       */
      @java.lang.Override
      public long getDeviceID() {
        return deviceID_;
      }
      /**
       * <code>int64 deviceID = 4;</code>
       * @param value The deviceID to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceID(long value) {
        
        deviceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 deviceID = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceID() {
        
        deviceID_ = 0L;
        onChanged();
        return this;
      }

      private Device.DeviceReading deviceReading_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Device.DeviceReading, Device.DeviceReading.Builder, Device.DeviceReadingOrBuilder> deviceReadingBuilder_;
      /**
       * <code>.DeviceReading deviceReading = 5;</code>
       * @return Whether the deviceReading field is set.
       */
      public boolean hasDeviceReading() {
        return deviceReadingBuilder_ != null || deviceReading_ != null;
      }
      /**
       * <code>.DeviceReading deviceReading = 5;</code>
       * @return The deviceReading.
       */
      public Device.DeviceReading getDeviceReading() {
        if (deviceReadingBuilder_ == null) {
          return deviceReading_ == null ? Device.DeviceReading.getDefaultInstance() : deviceReading_;
        } else {
          return deviceReadingBuilder_.getMessage();
        }
      }
      /**
       * <code>.DeviceReading deviceReading = 5;</code>
       */
      public Builder setDeviceReading(Device.DeviceReading value) {
        if (deviceReadingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deviceReading_ = value;
          onChanged();
        } else {
          deviceReadingBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.DeviceReading deviceReading = 5;</code>
       */
      public Builder setDeviceReading(
          Device.DeviceReading.Builder builderForValue) {
        if (deviceReadingBuilder_ == null) {
          deviceReading_ = builderForValue.build();
          onChanged();
        } else {
          deviceReadingBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.DeviceReading deviceReading = 5;</code>
       */
      public Builder mergeDeviceReading(Device.DeviceReading value) {
        if (deviceReadingBuilder_ == null) {
          if (deviceReading_ != null) {
            deviceReading_ =
              Device.DeviceReading.newBuilder(deviceReading_).mergeFrom(value).buildPartial();
          } else {
            deviceReading_ = value;
          }
          onChanged();
        } else {
          deviceReadingBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.DeviceReading deviceReading = 5;</code>
       */
      public Builder clearDeviceReading() {
        if (deviceReadingBuilder_ == null) {
          deviceReading_ = null;
          onChanged();
        } else {
          deviceReading_ = null;
          deviceReadingBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.DeviceReading deviceReading = 5;</code>
       */
      public Device.DeviceReading.Builder getDeviceReadingBuilder() {
        
        onChanged();
        return getDeviceReadingFieldBuilder().getBuilder();
      }
      /**
       * <code>.DeviceReading deviceReading = 5;</code>
       */
      public Device.DeviceReadingOrBuilder getDeviceReadingOrBuilder() {
        if (deviceReadingBuilder_ != null) {
          return deviceReadingBuilder_.getMessageOrBuilder();
        } else {
          return deviceReading_ == null ?
              Device.DeviceReading.getDefaultInstance() : deviceReading_;
        }
      }
      /**
       * <code>.DeviceReading deviceReading = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Device.DeviceReading, Device.DeviceReading.Builder, Device.DeviceReadingOrBuilder> 
          getDeviceReadingFieldBuilder() {
        if (deviceReadingBuilder_ == null) {
          deviceReadingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Device.DeviceReading, Device.DeviceReading.Builder, Device.DeviceReadingOrBuilder>(
                  getDeviceReading(),
                  getParentForChildren(),
                  isClean());
          deviceReading_ = null;
        }
        return deviceReadingBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:request)
    }

    // @@protoc_insertion_point(class_scope:request)
    private static final Device.request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Device.request();
    }

    public static Device.request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<request>
        PARSER = new com.google.protobuf.AbstractParser<request>() {
      @java.lang.Override
      public request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Device.request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeviceReading_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeviceReading_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014device.proto\"P\n\rDeviceReading\022\025\n\rdevic" +
      "eReading\030\001 \001(\003\022\020\n\010deviceID\030\002 \001(\t\022\026\n\016devi" +
      "ceDatetime\030\003 \001(\003\"Q\n\005reply\022\021\n\trequestID\030\001" +
      " \001(\t\022%\n\rdeviceReading\030\002 \001(\0132\016.DeviceRead" +
      "ing\022\016\n\006status\030\003 \001(\003\"\310\001\n\007request\022\021\n\treque" +
      "stID\030\001 \001(\t\022)\n\013requestType\030\002 \001(\0162\024.reques" +
      "t.RequestType\022\026\n\016deviceDatetime\030\003 \001(\003\022\020\n" +
      "\010deviceID\030\004 \001(\003\022%\n\rdeviceReading\030\005 \001(\0132\016" +
      ".DeviceReading\".\n\013RequestType\022\022\n\016INITIAL" +
      "IZATION\020\000\022\013\n\007CONTROL\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DeviceReading_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DeviceReading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeviceReading_descriptor,
        new java.lang.String[] { "DeviceReading", "DeviceID", "DeviceDatetime", });
    internal_static_reply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reply_descriptor,
        new java.lang.String[] { "RequestID", "DeviceReading", "Status", });
    internal_static_request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_request_descriptor,
        new java.lang.String[] { "RequestID", "RequestType", "DeviceDatetime", "DeviceID", "DeviceReading", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
